### ISSUE TITLE
The screen stuck at loading even on physical device ?

### ISSUE THREAD

**Issue by radha1990kumari** [Rajatkalsotra/Face-Recognition-with-Flutter#17]
```
D/libGLESv2(25436): DTS_GLAPI : DTS is not allowed for Package : com.rajatkalsotra.face_recognition
W/linker  (25436): /data/app/com.rajatkalsotra.face_recognition-1/lib/arm/libtensorflowlite_c.so: unused DT entry: type 0x1d arg 0x12ec
I/tflite  (25436): Initialized TensorFlow Lite runtime.
I/CameraManagerGlobal(25436): Connecting to camera service
V/ActivityThread(25436): updateVisibility : ActivityRecord{3c1ef5 token=android.os.BinderProxy@2abe2a3 {com.rajatkalsotra.face_recognition/com.rajatkalsotra.face_recognition.MainActivity}} show : true
E/SensorManager(25436): nativeGetSensorAtIndex: name, vendor - 0, K2HH Acceleration , STM
E/SensorManager(25436): nativeGetSensorAtIndex: name, vendor - 1, STK3013 Proximity Sensor, Sensortek
E/SensorManager(25436): nativeGetSensorAtIndex: name, vendor - 2, Screen Orientation Sensor, Samsung Electronics
D/SensorManager(25436): registerListener :: 0, K2HH Acceleration , 200000, 0,  
I/CameraManager(25436): Using legacy camera HAL.
I/CameraDeviceState(25436): Legacy camera service transitioning to state CONFIGURING
I/RequestThread-1(25436): Configure outputs: 2 surfaces configured.
D/Camera  (25436): app passed NULL surface
I/RequestThread-1(25436): configureOutputs - set take picture size to 320x240
D/libEGL  (25436): eglInitialize EGLDisplay = 0xce0e6404
D/mali_winsys(25436): new_window_surface returns 0x3000,  [320x240]-format:1
I/CameraDeviceState(25436): Legacy camera service transitioning to state IDLE
I/RequestQueue(25436): Repeating capture request set.
W/LegacyRequestMapper(25436): convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
I/Timeline(25436): Timeline: Activity_idle id: android.os.BinderProxy@2abe2a3 time:10156240
D/libEGL  (25436): eglInitialize EGLDisplay = 0xce0e62f4
I/CameraDeviceState(25436): Legacy camera service transitioning to state CAPTURING
I/RequestQueue(25436): Repeating capture request cancelled.
D/libEGL  (25436): eglInitialize EGLDisplay = 0xce0e62f4
I/CameraDeviceState(25436): Legacy camera service transitioning to state IDLE
I/CameraDeviceState(25436): Legacy camera service transitioning to state CONFIGURING
I/RequestThread-1(25436): Configure outputs: 2 surfaces configured.
D/libEGL  (25436): eglInitialize EGLDisplay = 0xce0e62f4
D/libEGL  (25436): eglInitialize EGLDisplay = 0xce0e62f4
D/libEGL  (25436): eglInitialize EGLDisplay = 0xce0e62f4
D/Camera  (25436): app passed NULL surface
D/libEGL  (25436): eglTerminate EGLDisplay = 0xce1eaf94
D/libEGL  (25436): eglTerminate EGLDisplay = 0xce1eaf94
D/libEGL  (25436): eglTerminate EGLDisplay = 0xce1eaf94
D/libEGL  (25436): eglTerminate EGLDisplay = 0xce1eaf94
D/libEGL  (25436): eglTerminate EGLDisplay = 0xce0e649c
D/libEGL  (25436): eglTerminate EGLDisplay = 0xce0e643c
D/libEGL  (25436): eglInitialize EGLDisplay = 0xce0e6404
D/mali_winsys(25436): new_window_surface returns 0x3000,  [320x240]-format:1
I/CameraDeviceState(25436): Legacy camera service transitioning to state IDLE
I/RequestQueue(25436): Repeating capture request set.
W/LegacyRequestMapper(25436): convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
D/libEGL  (25436): eglInitialize EGLDisplay = 0xce0e62f4
I/CameraDeviceState(25436): Legacy camera service transitioning to state CAPTURING
D/gralloc (25436): gralloc_lock_ycbcr success. format : 11, usage: 30, ycbcr.y: 0xee91e000, .cb: 0xee930c01, .cr: 0xee930c00, .ystride: 320 , .cstride: 320, .chroma_step: 2
D/gralloc (25436): gralloc_lock_ycbcr success. format : 11, usage: 3, ycbcr.y: 0xee91e000, .cb: 0xee930c01, .cr: 0xee930c00, .ystride: 320 , .cstride: 320, .chroma_step: 2
D/libEGL  (25436): eglInitialize EGLDisplay = 0xce0e62f4
D/gralloc (25436): gralloc_lock_ycbcr success. format : 11, usage: 30, ycbcr.y: 0xee91e000, .cb: 0xee930c01, .cr: 0xee930c00, .ystride: 320 , .cstride: 320, .chroma_step: 2
D/gralloc (25436): gralloc_lock_ycbcr success. format : 11, usage: 3, ycbcr.y: 0xee91e000, .cb: 0xee930c01, .cr: 0xee930c00, .ystride: 320 , .cstride: 320, .chroma_step: 2
D/libEGL  (25436): eglInitialize EGLDisplay = 0xce0e62f4
D/gralloc (25436): gralloc_lock_ycbcr success. format : 11, usage: 30, ycbcr.y: 0xee91e000, .cb: 0xee930c01, .cr: 0xee930c00, .ystride: 320 , .cstride: 320, .chroma_step: 2
D/gralloc (25436): gralloc_lock_ycbcr success. format : 11, usage: 3, ycbcr.y: 0xee91e000, .cb: 0xee930c01, .cr: 0xee930c00, .ystride: 320 , .cstride: 320, .chroma_step: 2
D/libEGL  (25436): eglInitialize EGLDisplay = 0xce0e62f4
D/gralloc (25436): gralloc_lock_ycbcr success. format : 11, usage: 30, ycbcr.y: 0xee91e000, .cb: 0xee930c01, .cr: 0xee930c00, .ystride: 320 , .cstride: 320, .chroma_step: 2
D/gralloc (25436): gralloc_lock_ycbcr success. format : 11, usage: 3, ycbcr.y: 0xee91e000, .cb: 0xee930c01, .cr: 0xee930c00, .ystride: 320 , .cstride: 320, .chroma_step: 2
D/libEGL  (25436): eglInitialize EGLDisplay = 0xce0e62f4
D/gralloc (25436): gralloc_lock_ycbcr success. format : 11, usage: 30, ycbcr.y: 0xee91e000, .cb: 0xee930c01, .cr: 0xee930c00, .ystride: 320 , .cstride: 320, .chroma_step: 2
D/libEGL  (25436): eglInitialize EGLDisplay = 0xce0e62f4
D/gralloc (25436): gralloc_lock_ycbcr success. format : 11, usage: 30, ycbcr.y: 0xd6b63000, .cb: 0xd6b75c01, .cr: 0xd6b75c00, .ystride: 320 , .cstride: 320, .chroma_step: 2
W/DynamiteModule(25436): Local module descriptor class for com.google.android.gms.vision.dynamite.face not found.
I/DynamiteModule(25436): Considering local module com.google.android.gms.vision.dynamite.face:0 and remote module com.google.android.gms.vision.dynamite.face:0
D/FaceNativeHandle(25436): Cannot load feature, fall back to load whole module.
W/DynamiteModule(25436): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
D/libEGL  (25436): eglInitialize EGLDisplay = 0xce0e62f4
I/DynamiteModule(25436): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:2703
I/DynamiteModule(25436): Selected remote version of com.google.android.gms.vision.dynamite, version >= 2703
V/DynamiteModule(25436): Dynamite loader version >= 2, using loadModule2NoCrashUtils
D/gralloc (25436): gralloc_lock_ycbcr success. format : 11, usage: 30, ycbcr.y: 0xd64a3000, .cb: 0xd64b5c01, .cr: 0xd64b5c00, .ystride: 320 , .cstride: 320, .chroma_step: 2
D/libEGL  (25436): eglInitialize EGLDisplay = 0xce0e62f4
W/ResourceType(25436): ResTable_typeSpec entry count inconsistent: given 67, previously 69
D/ResourcesManager(25436): For user 0 new overlays fetched Null
W/System  (25436): ClassLoader referenced unknown path: /data/data/com.google.android.gms/app_chimera/m/00000052/n/armeabi-v7a
W/System  (25436): ClassLoader referenced unknown path: /data/data/com.google.android.gms/app_chimera/m/00000052/n/armeabi
D/ResourcesManager(25436): For user 0 new overlays fetched Null
W/DynamiteModule(25436): Local module descriptor class for com.google.android.gms.vision.face not found.
I/DynamiteModule(25436): Considering local module com.google.android.gms.vision.face:0 and remote module com.google.android.gms.vision.face:0
E/FaceDetectorCreator(25436): Error loading optional module com.google.android.gms.vision.face
E/FaceDetectorCreator(25436): hh: No acceptable module found. Local version is 0 and remote version is 0.
E/FaceDetectorCreator(25436): 	at hk.e(:com.google.android.gms.dynamite_dynamitemodulesa@212116046@21.21.16 (040306-0):84)
E/FaceDetectorCreator(25436): 	at com.google.android.gms.vision.face.ChimeraNativeFaceDetectorCreator.newFaceDetector(:com.google.android.gms.dynamite_dynamitemodulesa@212116046@21.21.16 (040306-0):2)
E/FaceDetectorCreator(25436): 	at jl.a(:com.google.android.gms.dynamite_dynamitemodulesa@212116046@21.21.16 (040306-0):4)
E/FaceDetectorCreator(25436): 	at aq.onTransact(:com.google.android.gms.dynamite_dynamitemodulesa@212116046@21.21.16 (040306-0):4)
E/FaceDetectorCreator(25436): 	at android.os.Binder.transact(Binder.java:387)
E/FaceDetectorCreator(25436): 	at com.google.android.gms.internal.vision.zza.transactAndReadException(Unknown Source)
E/FaceDetectorCreator(25436): 	at com.google.android.gms.vision.face.internal.client.zzh.zza(Unknown Source)
E/FaceDetectorCreator(25436): 	at com.google.android.gms.vision.face.internal.client.zza.zza(Unknown Source)
E/FaceDetectorCreator(25436): 	at com.google.android.gms.internal.vision.zzl.zzp(Unknown Source)
E/FaceDetectorCreator(25436): 	at com.google.android.gms.vision.face.internal.client.zza.<init>(Unknown Source)
E/FaceDetectorCreator(25436): 	at com.google.android.gms.vision.face.FaceDetector$Builder.build(Unknown Source)
E/FaceDetectorCreator(25436): 	at com.google.android.gms.internal.firebase_ml.zziv.zzfm(Unknown Source)
E/FaceDetectorCreator(25436): 	at com.google.android.gms.internal.firebase_ml.zzhr.zzfp(Unknown Source)
E/FaceDetectorCreator(25436): 	at com.google.android.gms.internal.firebase_ml.zzhr.call(Unknown Source)
E/FaceDetectorCreator(25436): 	at com.google.android.gms.internal.firebase_ml.zzhg.zza(Unknown Source)
E/FaceDetectorCreator(25436): 	at com.google.android.gms.internal.firebase_ml.zzhh.run(Unknown Source)
E/FaceDetectorCreator(25436): 	at android.os.Handler.handleCallback(Handler.java:739)
E/FaceDetectorCreator(25436): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/FaceDetectorCreator(25436): 	at android.os.Looper.loop(Looper.java:148)
E/FaceDetectorCreator(25436): 	at android.os.HandlerThread.run(HandlerThread.java:61)
I/Vision  (25436): Request download for engine face
W/FaceNativeHandle(25436): Native handle not yet available. Reverting to no-op handle.

```
I suspect it is not able to use firebase model

**Comment by Rajatkalsotra** [comment]
Yes, I too think this error is associated with firebase module which detects the face.
